// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEOAkq_wErV_16tRoA3ovlfvsuZjx6Rc4',
    appId: '1:513570110811:web:b2935bb8a03b86850b6e7e',
    messagingSenderId: '513570110811',
    projectId: 'eatassured-cu',
    authDomain: 'eatassured-cu.firebaseapp.com',
    storageBucket: 'eatassured-cu.appspot.com',
    measurementId: 'G-PSZLY7C13L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Br8xw4qmA-jmJcsssq1gCDzMoiWVfc4',
    appId: '1:513570110811:android:7b255df21376cff40b6e7e',
    messagingSenderId: '513570110811',
    projectId: 'eatassured-cu',
    storageBucket: 'eatassured-cu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp_cLvon020y6z5KCVws9xQ72jIRpFHac',
    appId: '1:513570110811:ios:a528520c85bd64420b6e7e',
    messagingSenderId: '513570110811',
    projectId: 'eatassured-cu',
    storageBucket: 'eatassured-cu.appspot.com',
    iosClientId: '513570110811-eepvu1o5nq9hk7rlbn9uihmmg1nh0erp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatassured',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp_cLvon020y6z5KCVws9xQ72jIRpFHac',
    appId: '1:513570110811:ios:aec6dbbf90dc01ee0b6e7e',
    messagingSenderId: '513570110811',
    projectId: 'eatassured-cu',
    storageBucket: 'eatassured-cu.appspot.com',
    iosClientId: '513570110811-o75mkb3nadq109g8rthbm27uj4ms5slm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatassured.RunnerTests',
  );
}
